name: Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pytest requests allure-pytest

      - name: Run tests
        env:
          FOOTBALL_TOKEN: ${{ secrets.FOOTBALL_TOKEN }}
        run: pytest tests/ -v --alluredir=allure-results
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results

      - name: Publish report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history