name: Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pytest requests

      - name: Run tests
        run: pytest test_first.py test_fixtures.py test_params.py test_api.py test_post.py -v

      - name: Run tests
        env:
          FOOTBALL_TOKEN: ${{ secrets.FOOTBALL_TOKEN }}
        run: pytest test_first.py test_fixtures.py test_params.py test_api.py test_post.py test_football.py -v